### ISSUE TITLE
demo issue

### ISSUE THREAD

**Issue by procmail** [MrSaints/Morphist#2]
Hi,

In your demo (http://morphist.fyianlai.com/), if one chooses "fadeInDownBig" as animation in, and then for animation out, an effect from the "Attention Seekers" section (eg tada), then the animation stops. The next object will not be rotated in.

This occurs not only for "fadeInDownBig", but also for any of the "\* Entrances" effects as animation in.

Edit:
Randomly trying, it seems the combination lightSpeedIn and bounceOut has the same problem as well.

**Comment by procmail** [comment]
Hi,

Sorry, it's me again. 

In the demo if I choose Flash and Flash, or Tada and Tada, the demo stops working.

**Comment by MrSaints** [comment]
Hey @procmail,

Thanks again for the report.

I'm aware of this. It's because I haven't updated the JS plugin file for the demo itself.
I'll resolve it ASAP and get back to you.

Many thanks again :+1:

**Comment by procmail** [comment]
Hi Ian,

You're welcome. 

The reason I reported it was because I noticed it on my own web pages despite using the latest Morphist plugin, which was why I went to test on your demo site. 

Looking forward to your fix :)

Regards,

Eric

**Comment by MrSaints** [comment]
Hi again @procmail,

I've resolved the issue in f3f31059816dc420da5a0377d2346f8cfd836f98 (master) and 4d152fdbddb0176a0d367bf6dc301611aac37fe5 (gh-pages).

Many thanks again for the report.

It turned out to be an interesting issue which only occurs when the in and out animation types are the same. As we are technically _reapplying_ the same animation class, browser reflow was not triggered and as a result, the out animation was not fired causing the cycle to terminate prematurely.

I added a check to force browser reflow if the animation types are the same (although I think this is quite uncommon in production use, nevertheless, it's there).

Thanks again!

**Comment by procmail** [comment]
Hi Ian,

Sorry to bother you again.

On my own pages, using v2.0.1, the following happens when I choose bounce-bounce and tada-tada animations, in Safari 8.0.2
1) first item animates fine, then animates out
2) second item doesn’t show up at all.

However, it seems to be showing fine in Chrome.

Also, your demo page Preview tweets aren’t showing at all on Safari, but works fine on Chrome. I’m not sure if this happened prior to your latest fix as I didn’t use Safari to browse the demo page previously.

Regards,

Eric

**Comment by MrSaints** [comment]
Hey @procmail, it's no bother at all! Thank you so much for the reports and pull request.
I haven't gotten a chance to install Safari to try it out, but I'll look into it ASAP :stuck_out_tongue_closed_eyes:
